version: "3.9"
services:
  servlet:
    build: .
    ports:
      - "7777:8080"
    depends_on:
      - postgres_db
  postgres_db:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: qwerty
